from pathlib import Path
from datetime import datetime
import csv

from config import MIKROTIK



def validate_routeros_value(value):

    forbidden = [
        " ",
        '"',
        "'",
        ";",
        "\\",
        "\n",
        "\r"
    ]


    for char in forbidden:

        if char in value:

            return False


    return True





def validate_export(
    vouchers,
    profile
):

    if not vouchers:

        raise ValueError(
            "No vouchers to export."
        )


    if not validate_routeros_value(profile):

        raise ValueError(
            "Invalid MikroTik profile name."
        )


    for voucher in vouchers:

        if not validate_routeros_value(voucher):

            raise ValueError(
                f"Invalid voucher code: {voucher}"
            )


    return True


def save_export_history(
    filename,
    profile,
    quantity
):

    folder = Path(
        "exports"
    )

    folder.mkdir(
        exist_ok=True
    )


    history_file = (
        folder
        /
        "export_history.csv"
    )


    file_exists = history_file.exists()



    with open(
        history_file,
        "a",
        newline="",
        encoding="utf-8"
    ) as file:


        writer = csv.writer(
            file
        )


        if not file_exists:

            writer.writerow(
                [
                    "filename",
                    "hotspot_server",
                    "profile",
                    "quantity",
                    "created"
                ]
            )


        writer.writerow(
            [
                str(filename),
                MIKROTIK["hotspot_server"],
                profile,
                quantity,
                datetime.now().strftime(
                    "%Y-%m-%d %H:%M"
                )
            ]
        )


def save_import_file(
    vouchers,
    profile,
    limit_uptime
):

    validate_export(
        vouchers,
        profile
    )


    folder = Path(
        "imports"
    )

    folder.mkdir(
        exist_ok=True
    )


    filename = (
        folder
        /
        (
            "import_"
            +
            datetime.now().strftime(
                "%Y%m%d_%H%M%S"
            )
            +
            ".rsc"
        )
    )


    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:


        file.write(
            "/ip hotspot user\n\n"
        )


        for voucher in vouchers:


            file.write(
                f'add server={MIKROTIK["hotspot_server"]} '
                f'name={voucher} '
                f'password={voucher} '
                f'profile="{profile}" '
                f'limit-uptime={limit_uptime} '
                f'comment="Generated by JeffWiFi"\n'
            )


        save_export_history(
        filename,
        profile,
        len(vouchers)
    )


    return filename